engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
  rubocop:
    enabled: true
