# Fog custom enforced styles

LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
SignalException:
  Enabled: false
RaiseArgs:
  Enabled: false
ParameterLists:
  Enabled: false
AbcSize:
  Enabled: false
RedundantBegin:
  Enabled: false
PerceivedComplexity:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
RescueException:
  Enabled: false
NestedParenthesizedCalls:
  Enabled: false
