LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
SignalException:
  Enabled: false
RaiseArgs:
  Enabled: false
ParameterLists:
  Enabled: false
AbcSize:
  Enabled: false
NestedParenthesizedCalls:
  Enabled: false

