# Fog custom enforced styles

LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
SignalException:
  Enabled: false
RaiseArgs:
  Enabled: false
ParameterLists:
  Enabled: false
AbcSize:
  Enabled: false
RedundantBegin:
  Enabled: false
PerceivedComplexity:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
RescueException:
  Enabled: false
NestedParenthesizedCalls:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  # If true, strings which span multiple lines using \ for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
